// Topology 4 is an implementation with channels of a concurrency pattern
// which solves the problem:
// To process a variable number of tasks (stream) while preserving original order.
// It uses a Pipeline Topology combined with a Fan-Out/Fan-In Worker Pool
// with Channels of Channels (chan chan Result),
// with a task generator goroutine and a supervisor goroutine.

package main

import "fmt"

// maxWorkers is a chosen number of workers.
const maxWorkers = 8

type data int
type Result struct{ Data data }

// A taskEnvelope will be scheduled to be sent to the workers.
type taskEnvelope struct {
	task  data        // The actual work to do
	reply chan Result // The private, unbuffered channel to reply with result
}

func main() {
	// Set up the throttling channels
	// Use reasonable buffer, the same for tasks and order channel
	const buffer = 5
	tasksCh := make(chan taskEnvelope, buffer)
	orderCh := make(chan chan Result, buffer)

	// Initialize the input tasks stream
	stream := &TaskStream{} // Starts at 0

	// Fan-out producer / task generator as background stream reader
	go func() {
		// Keep reading until the stream source is exhausted
		for stream.Next() {
			task := stream.GetTask()
			reply := make(chan Result)

			// 1. Send to workers for concurrent exectuion
			tasksCh <- taskEnvelope{task: task, reply: reply}

			// 2. Send the reply channel to ordering channel to track the order
			orderCh <- reply
		}
		// Stream ended
		close(tasksCh) // No more tasks will be created
		close(orderCh) // No more order placeholders will be tracked
	}()

	// A fixed number of workers pull envelopes from tasksCh
	for _ = range maxWorkers {
		go func() {
			for envelope := range tasksCh {
				processed := process(envelope.task)
				// The worker will hold up result until earlier ordered tasks are sequenced
				envelope.reply <- Result{processed} // Blocks until Sequencer is ready
			}
		}()
	}

	// Sequencer / Fan-in consumer
	for reply := range orderCh {
		res := <-reply // Blocks in the exact order they were generated by the stream
		handleResultOrdered(res)
	}
}

// process is an example processing function of task data, wich returns data
func process(d data) data {
	return d
}

// handleResultOrdered is an example result gathering / post-processing function
func handleResultOrdered(r Result) {
	fmt.Println(r.Data)
}

// TaskStream is an example streamer of tasks
type TaskStream struct {
	val int
}

func (s *TaskStream) Next() bool {
	// Stops the stream at 20 items.
	if s.val < 20 {
		return true
	}
	return false
}

func (s *TaskStream) GetTask() data {
	task := data(s.val)
	s.val++ // Advance the count for the next iteration
	return task
}
